coverage:
  range: 50..75
  status:
    # Prevent small variations of coverage from failing CI.
    project:
      default:
        threshold: 10% # TODO: reduce once we have a better coverage
    patch: off
ignore:
  - internal/version
