project_name: kubectl-vpa-recommendation
release:
  prerelease: auto
  draft: true
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - binary: kubectl-vpa-recommendation
    main: ./cmd/kubectl-vpa-recommendation
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s
      - -w
      - -X github.com/wI2L/kubectl-vpa-recommendation/internal/version.buildDate={{ .Date }}
      - -X github.com/wI2L/kubectl-vpa-recommendation/internal/version.gitCommit={{ .FullCommit }}
      - -X github.com/wI2L/kubectl-vpa-recommendation/internal/version.gitVersion={{ .Version }}
      - -X github.com/wI2L/kubectl-vpa-recommendation/internal/version.gitTreeState={{ .Env.GIT_TREE_STATE }}
      - -X github.com/wI2L/kubectl-vpa-recommendation/internal/version.gitVersionMajor={{ .Major }}
      - -X github.com/wI2L/kubectl-vpa-recommendation/internal/version.gitVersionMinor={{ .Minor }}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  use: github