name: ci
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          args: -c .golangci.yaml
          only-new-issues: true
  test:
    name: Tests
    needs:
      - lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go:
          - "1.17.x"
          - "1.18.x"
          - "1.19.x"
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-
      - name: Run tests
        run: make test
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.txt